// Turns a local export of the hosted project (supabase/.backups/*.json) into
// SQL that recreates those rows exactly in a DISPOSABLE rehearsal database,
// on top of the schema at 20260124 — so the reconciliation can be rehearsed
// against the real data before it touches the hosted project.
//
//   node scripts/data-rebuild/snapshot-to-sql.mjs <export.json> > load.sql
//
// Loading runs with session_replication_role = replica, the way a data-only
// restore does, because the rows being copied were already accepted by the
// live triggers once. Never run its output against a real project: it
// replaces the application data wholesale.
import { readFileSync } from 'node:fs'

const file = process.argv[2]
if (!file) {
  console.error('usage: snapshot-to-sql.mjs <export.json>')
  process.exit(1)
}
const snap = JSON.parse(readFileSync(file, 'utf8'))

const tag = '$snap$'
const lit = (v) => {
  const s = JSON.stringify(v ?? [])
  if (s.includes(tag)) throw new Error('export contains the dollar-quote tag')
  return `${tag}${s}${tag}::jsonb`
}
// Only real stored columns are written (generated ones are recomputed), and
// identity values are kept as exported.
const populate = (table, rows) => `select pg_temp.load('${table}', ${lit(rows)});`

const out = []
out.push('-- generated by scripts/data-rebuild/snapshot-to-sql.mjs — DISPOSABLE REHEARSAL DATABASE ONLY')
out.push(`-- source export: project ${snap.project_ref}, exported ${snap.exported_at}`)
out.push('begin;')
out.push(`create function pg_temp.load(t regclass, rows jsonb) returns void language plpgsql as $fn$
declare cols text;
begin
  select string_agg(quote_ident(attname), ', ' order by attnum) into cols
  from pg_attribute where attrelid = t and attnum > 0 and not attisdropped and attgenerated = '';
  execute format('insert into %s (%s) overriding system value select %s from jsonb_populate_recordset(null::%s, $1)',
                 t, cols, cols, t) using rows;
end $fn$;`)
out.push('set local session_replication_role = replica;')
for (const t of [
  'activity', 'task_requirements', 'proposal_requirements', 'spec_measurements', 'clause_status',
  'handover_notes', 'tasks', 'task_proposals', 'specs', 'milestone_sections', 'milestones',
  'meetings', 'meeting_template', 'finance_entries', 'member_roles', 'members', 'seasons',
  'subteams', 'regulation_documents',
]) out.push(`delete from ${t};`)
out.push('delete from auth.users;')

out.push(`insert into auth.users (id, email, created_at)
  select (e->>'id')::uuid, e->>'email', (e->>'created_at')::timestamptz from jsonb_array_elements(${lit(snap.auth_users)}) e;`)
out.push(populate('regulation_documents', snap.regulation_documents))
out.push(populate('members', snap.members))
out.push(populate('seasons', snap.seasons))
out.push(populate('subteams', snap.subteams))
out.push(populate('member_roles', snap.member_roles))
out.push(populate('milestones', snap.milestones))
out.push(populate('milestone_sections', snap.milestone_sections))
out.push(populate('meetings', snap.meetings))
out.push(populate('meeting_template', snap.meeting_template))
out.push(populate('task_proposals', snap.task_proposals))
out.push(populate('tasks', snap.tasks))
out.push(populate('handover_notes', snap.handover_notes))
out.push(populate('clause_status', snap.clause_status))
out.push(populate('task_requirements', snap.task_requirements))
out.push(populate('proposal_requirements', snap.proposal_requirements))
out.push(populate('specs', snap.specs))
out.push(populate('spec_measurements', snap.spec_measurements))
out.push(populate('finance_entries', snap.finance_entries))
out.push(populate('activity', snap.activity))
out.push(`select setval(pg_get_serial_sequence('activity', 'id'), greatest((select max(id) from activity), 1));`)

// Clause text comes from the migrations (the export proves it identical by
// hash); department and page come from the export.
out.push(`update clauses c set subteam_key = e->>1, source_page = (e->>2)::int
  from jsonb_array_elements(${lit(snap.clause_classification)}) e where c.clause_key = e->>0;`)
out.push('commit;')

out.push(`do $$ begin
  if (select md5(string_agg(concat_ws('|', clause_key, printed_ref, section, article, article_title, group_title,
        subteam_key, body, obligation, criticality, phase, milestone_key, is_team_duty, specs::text, regs_ref, source_page),
        E'\\n' order by clause_key collate "C")) from clauses) <> '${snap.clauses_content_md5}' then
    raise exception 'rehearsal clauses differ from the hosted export';
  end if;
end $$;`)

process.stdout.write(out.join('\n') + '\n')
