#!/usr/bin/env python3
"""
Turn the handoff data files into SQL.

Reads   ../handoff/seed_clauses.csv   (1,146 regulation clauses)
        ../handoff/seed_reference.json (subteams, milestones, spec sheet, people)

Writes  supabase/migrations/20260101000001_reference_data.sql
            The regulations book and the structures that hang off it:
            subteams, clauses, the season, milestones, milestone sections,
            spec-sheet rows. This is edition reference data — it belongs in
            every environment, so it is a migration, not a dev seed.

        supabase/seed.sql
            LOCAL DEVELOPMENT ONLY. Demo logins, the roster, and the team's
            September 2026 topics/tasks/meetings so the app has something to
            show on a fresh machine. `supabase db reset` runs this; production
            never does.

Re-run after dropping in a new edition's seed_clauses.csv:
    python3 scripts/generate_seed_sql.py
"""
import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
HANDOFF = os.path.join(os.path.dirname(REPO), "handoff")

SEASON = "2026/27"


def q(value):
    """Quote a value as a SQL literal. None and '' both become NULL."""
    if value is None or value == "":
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


def qbool(value):
    return "true" if value in (True, "true", "True", 1) else "false"


def qnum(value):
    return "null" if value is None or value == "" else str(value)


def load():
    with open(os.path.join(HANDOFF, "seed_clauses.csv"), encoding="utf-8") as fh:
        clauses = list(csv.DictReader(fh))
    with open(os.path.join(HANDOFF, "seed_reference.json"), encoding="utf-8") as fh:
        ref = json.load(fh)
    return clauses, ref


# --------------------------------------------------------------- reference data
def build_reference(clauses, ref):
    out = []
    w = out.append
    w("-- GENERATED by scripts/generate_seed_sql.py — do not hand-edit.")
    w("-- Edition reference data: the regulations book and its scaffolding.")
    w("-- Idempotent: re-running refreshes rows in place.")
    w("")

    # -- subteams ------------------------------------------------------------
    w("-- 14 subsystems. RACEOP is parked: those rules only bite at the Final Event.")
    w("insert into subteams (key, name, book_section, description, is_parked, sort_order) values")
    rows = []
    for i, s in enumerate(ref["subteams"]):
        rows.append(
            f"  ({q(s['id'])}, {q(s['name'])}, {q(s['sec'])}, {q(s.get('desc'))}, "
            f"{qbool(s['id'] == 'RACEOP')}, {i})"
        )
    w(",\n".join(rows))
    w("on conflict (key) do update set")
    w("  name = excluded.name, book_section = excluded.book_section,")
    w("  description = excluded.description, sort_order = excluded.sort_order;")
    w("")

    # -- season --------------------------------------------------------------
    ident = ref["identity"]
    w("-- The current season. Everything the team types hangs off this row.")
    w("insert into seasons (label, edition, regs_ref, category, club_name, university, is_current)")
    w(f"values ({q(SEASON)}, {q(ident['edition'])}, {q(ident['regsRef'])}, "
      f"{q(ident['category'])}, {q(ident['club'])}, {q(ident['university'])}, true)")
    w("on conflict (label) do nothing;")
    w("")

    # -- clauses -------------------------------------------------------------
    w(f"-- The regulations book: {len(clauses)} clauses, MS2627 Rev.01, Section D excluded (eFuel).")
    w("-- clause_key is unique; printed_ref is what the book prints. They differ for")
    w("-- E.5.4.5 and F.5.2.3, which the Organization numbered twice. Show printed_ref.")
    cols = ("clause_key, printed_ref, section, article, article_title, group_title, "
            "subteam_key, body, obligation, criticality, phase, milestone_key, "
            "is_team_duty, specs")
    for start in range(0, len(clauses), 200):
        chunk = clauses[start:start + 200]
        w(f"insert into clauses ({cols}) values")
        rows = []
        for c in chunk:
            rows.append(
                "  (" + ", ".join([
                    q(c["clause_key"]), q(c["printed_ref"]), q(c["section"]),
                    str(int(c["article"])), q(c["article_title"]), q(c["group_title"]),
                    q(c["subteam_key"]), q(c["body"]), q(c["obligation"]),
                    q(c["criticality"]), q(c["phase"]), q(c["milestone_key"]),
                    qbool(c["is_team_duty"]), q(c["specs"] or "[]") + "::jsonb",
                ]) + ")"
            )
        w(",\n".join(rows))
        w("on conflict (clause_key) do update set")
        w("  printed_ref = excluded.printed_ref, section = excluded.section,")
        w("  article = excluded.article, article_title = excluded.article_title,")
        w("  group_title = excluded.group_title, subteam_key = excluded.subteam_key,")
        w("  body = excluded.body, obligation = excluded.obligation,")
        w("  criticality = excluded.criticality, phase = excluded.phase,")
        w("  milestone_key = excluded.milestone_key,")
        w("  is_team_duty = excluded.is_team_duty, specs = excluded.specs;")
        w("")

    # -- milestones ----------------------------------------------------------
    w("-- MS1 deliverables. MS1-7 happens at the Final Event and has no published")
    w("-- window, so opens_on/due_on stay null and the UI renders TBC. Never a guess.")
    for m in ref["milestones"]:
        blocking = qbool(m.get("blocking", False))
        w("insert into milestones (key, season_id, ordinal, name, aim, article_ref,")
        w("                        opens_on, due_on, max_points, is_blocking, notes)")
        w(f"select {q(m['id'])}, s.id, {m['n']}, {q(m['name'])}, {q(m.get('aim'))},")
        w(f"       {q(m.get('art'))}, {q(m.get('opens'))}::date, {q(m.get('due'))}::date,")
        w(f"       {m.get('points', 0)}, {blocking}, {q(m.get('when_note'))}")
        w(f"from seasons s where s.label = {q(SEASON)}")
        w("on conflict (key) do update set")
        w("  ordinal = excluded.ordinal, name = excluded.name, aim = excluded.aim,")
        w("  article_ref = excluded.article_ref, opens_on = excluded.opens_on,")
        w("  due_on = excluded.due_on, max_points = excluded.max_points,")
        w("  is_blocking = excluded.is_blocking, notes = excluded.notes;")
        w("")

    # -- milestone sections --------------------------------------------------
    w("-- The section checklist inside each deliverable.")
    w("insert into milestone_sections (milestone_key, ordinal, name) values")
    rows = []
    for m in ref["milestones"]:
        for i, name in enumerate(m.get("sections", []), start=1):
            rows.append(f"  ({q(m['id'])}, {i}, {q(name)})")
    w(",\n".join(rows))
    w("on conflict (milestone_key, ordinal) do update set name = excluded.name;")
    w("")

    # -- specs ---------------------------------------------------------------
    w("-- Spec sheet. Pass/fail is NEVER stored — read it from the spec_verdicts view.")
    w("-- 'Competition number' is a range (1-99), which the view reports as unmeasured")
    w("-- by design: a range needs a human to read it, not a comparison.")
    for i, s in enumerate(ref["specsheet"]):
        target = s.get("target")
        numeric = isinstance(target, (int, float))
        w("insert into specs (season_id, parameter, comparator, target, target_text,")
        w("                   unit, clause_key, condition, sort_order)")
        w(f"select s.id, {q(s['param'])}, {q(s['op'])}, {qnum(target) if numeric else 'null'},")
        w(f"       {'null' if numeric else q(target)}, {q(s.get('unit'))},")
        w(f"       c.clause_key, {q(s.get('cond'))}, {i}")
        w(f"from seasons s")
        w(f"left join clauses c on c.clause_key = {q(s.get('ref'))}")
        w(f"where s.label = {q(SEASON)}")
        w("  and not exists (select 1 from specs x")
        w(f"                  where x.season_id = s.id and x.parameter = {q(s['param'])});")
        w("")

    return "\n".join(out) + "\n"


# ------------------------------------------------------------------- dev seed
def build_dev_seed(ref):
    """Local-only: demo logins + the roster + the team's real Sept 2026 notes."""
    out = []
    w = out.append
    w("-- GENERATED by scripts/generate_seed_sql.py — do not hand-edit.")
    w("--")
    w("-- LOCAL DEVELOPMENT ONLY. `supabase db reset` runs this file; a hosted")
    w("-- Supabase project never does. It creates demo logins so you can open the")
    w("-- app on a fresh machine without wiring up real accounts.")
    w("--")
    w("--   every demo login is  <initials>@sdumotorbike.test  /  paddock123")
    w("--   e.g.  mic@sdumotorbike.test  (Team Lead, board member)")
    w("--")
    w("-- Real accounts are created by the board in the Supabase dashboard, and a")
    w("-- matching `members` row is what actually grants access. See README.md.")
    w("")
    w("-- Demo auth users. Deleting these cascades to their members rows.")
    w("delete from auth.users where email like '%@sdumotorbike.test';")
    w("")

    board = {"mic", "and", "pio"}  # president, vice-president, treasurer
    for m in ref["members"]:
        email = f"{m['id']}@sdumotorbike.test"
        w("insert into auth.users (instance_id, id, aud, role, email, encrypted_password,")
        w("                        email_confirmed_at, raw_app_meta_data, raw_user_meta_data,")
        w("                        created_at, updated_at)")
        w(f"values ('00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated',")
        w(f"        'authenticated', {q(email)}, crypt('paddock123', gen_salt('bf')), now(),")
        w("        '{\"provider\":\"email\",\"providers\":[\"email\"]}'::jsonb, '{}'::jsonb,")
        w("        now(), now());")
        w("")
        # GoTrue needs an identity row before it will accept a password login.
        w("insert into auth.identities (provider_id, user_id, identity_data, provider,")
        w("                             last_sign_in_at, created_at, updated_at)")
        w("select u.id::text, u.id,")
        w("       jsonb_build_object('sub', u.id::text, 'email', u.email, 'email_verified', true),")
        w("       'email', now(), now(), now()")
        w(f"from auth.users u where u.email = {q(email)};")
        w("")
        w("insert into members (id, full_name, role, study_year, skills, status, is_board, notes)")
        w(f"select u.id, {q(m['name'])}, {q(m['role'])}, {q(m.get('year'))}, {q(m.get('skills'))},")
        w(f"       {q('active' if m.get('active') else 'alumni')}, {qbool(m['id'] in board)}, {q(m.get('note'))}")
        w(f"from auth.users u where u.email = {q(email)};")
        w("")

    def member_ref(key):
        """SQL scalar for a member id, or null when the seed has no owner."""
        if not key:
            return "null"
        return f"(select id from members where id = (select id from auth.users where email = '{key}@sdumotorbike.test'))"

    # -- topics --------------------------------------------------------------
    w("-- The ten live questions as of 2026-09-08.")
    for t in ref["topics"]:
        w("insert into topics (season_id, title, context, state, owner_id, decision, raised_by, raised_on)")
        w(f"select s.id, {q(t['title'])}, {q(t.get('why'))}, {q(t['status'])}::topic_state,")
        w(f"       {member_ref(t.get('owner'))}, {q(t.get('decision'))},")
        w(f"       {member_ref(t.get('by'))}, {q(t.get('raised'))}::date")
        w(f"from seasons s where s.label = {q(SEASON)}")
        w(f"  and not exists (select 1 from topics x where x.title = {q(t['title'])});")
        w("")

    # -- tasks ---------------------------------------------------------------
    # The spreadsheet names owners in prose ("All members", "Piotr / Michelle").
    # Only a name that resolves to exactly one person becomes an owner_id; the
    # rest stay in `detail` rather than being invented into a single owner.
    name_to_key = {"michelle": "mic", "andrzej": "and", "aditya": "adi",
                   "piotr": "pio", "mate": "mat", "claudiu": "cla"}
    w("-- The September 2026 to-do list. Owners written in prose in the source")
    w("-- spreadsheet ('All members', 'Piotr / Michelle') resolve to no single")
    w("-- person, so they stay in the detail text instead of being guessed at.")
    for t in ref["tasks"]:
        owner_raw = (t.get("owner") or "").strip()
        owner_key = name_to_key.get(owner_raw.lower(), "")
        detail_bits = []
        if t.get("goal"):
            detail_bits.append(f"Goal: {t['goal']}")
        if owner_raw and not owner_key:
            detail_bits.append(f"Assigned in the source sheet to: {owner_raw}")
        detail = " — ".join(detail_bits)
        w("insert into tasks (season_id, title, detail, owner_id, due_date, state, starred)")
        w(f"select s.id, {q(t['title'])}, {q(detail)}, {member_ref(owner_key)},")
        w(f"       {q(t.get('due'))}::date, {q(t['status'])}::task_state, {qbool(t.get('prio') == 1)}")
        w(f"from seasons s where s.label = {q(SEASON)}")
        w(f"  and not exists (select 1 from tasks x where x.title = {q(t['title'])});")
        w("")

    # -- meetings ------------------------------------------------------------
    w("-- Meeting minutes already held.")
    for m in ref["meetings"]:
        summary = m.get("goal", "")
        if m.get("points"):
            summary = (summary + "\n\n" if summary else "") + "\n".join(
                f"- {p}" for p in m["points"])
        w("insert into meetings (season_id, held_on, attendees, summary)")
        w(f"select s.id, {q(m['date'])}::date, {q(m.get('who'))}, {q(summary)}")
        w(f"from seasons s where s.label = {q(SEASON)}")
        w(f"  and not exists (select 1 from meetings x")
        w(f"                  where x.held_on = {q(m['date'])}::date and x.attendees = {q(m.get('who'))});")
        w("")

    w("-- Handover notes start empty, one per subteam, ready to be written into.")
    w("insert into handover_notes (season_id, subteam_key, body)")
    w(f"select s.id, st.key, '' from seasons s cross join subteams st where s.label = {q(SEASON)}")
    w("on conflict (season_id, subteam_key) do nothing;")
    w("")

    return "\n".join(out) + "\n"


def main():
    clauses, ref = load()
    ref_path = os.path.join(REPO, "supabase", "migrations",
                            "20260101000001_reference_data.sql")
    seed_path = os.path.join(REPO, "supabase", "seed.sql")

    with open(ref_path, "w", encoding="utf-8") as fh:
        fh.write(build_reference(clauses, ref))
    with open(seed_path, "w", encoding="utf-8") as fh:
        fh.write(build_dev_seed(ref))

    print(f"wrote {ref_path} ({len(clauses)} clauses, {len(ref['subteams'])} subteams, "
          f"{len(ref['milestones'])} milestones, {len(ref['specsheet'])} specs)")
    print(f"wrote {seed_path} ({len(ref['members'])} members, {len(ref['topics'])} topics, "
          f"{len(ref['tasks'])} tasks, {len(ref['meetings'])} meetings)")


if __name__ == "__main__":
    main()
