#!/usr/bin/env python3
"""
Build mock-data.sql for a HOSTED Supabase project: first the edition's
reference data (season, subsystems, the 1,146 clauses, milestones, spec sheet —
the same rows as migration 20260101000001, safe to re-run), then the demo
roster, topics, tasks and meetings from ../handoff/seed_reference.json.

    python3 scripts/make_mock_data_sql.py

Then paste mock-data.sql into Supabase → SQL Editor → Run. The file:
  * creates one login per demo person, all sharing ONE random password that is
    printed below and nowhere else. Never the old `paddock123`: that one is
    written in this repo, so on a real site anyone could sign in with it;
  * refuses to run twice — the second time nothing is changed;
  * runs as one transaction: all of it lands, or none of it.

It contains that password, so it is git-ignored. Delete it after use.
"""
import os
import re
import secrets
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import generate_seed_sql as gen  # noqa: E402  (the one source of the mock data)

OUT = os.path.join(gen.REPO, "mock-data.sql")

GUARD = """-- Stop, changing nothing, if this has run before or the schema is missing.
do $$
begin
  if exists (select 1 from auth.users where email like '%@sdumotorbike.test') then
    raise exception 'The mock data is already loaded. Nothing was changed.';
  end if;
  if not exists (select 1 from seasons where label = '2026/27') then
    raise exception 'Season 2026/27 is missing. Run supabase/migrations first, in order.';
  end if;
end $$;
"""

SUMMARY = """
-- What is there now.
select 'regulation clauses' as what, count(*) as how_many from clauses
union all select 'current season', count(*) from seasons where is_current
union all select 'people on the roster', count(*) from members
union all select 'people with a privileged role', count(*) from member_roles
union all select 'topics', count(*) from topics
union all select 'tasks', count(*) from tasks
union all select 'meetings', count(*) from meetings;
"""


def main():
    clauses, ref = gen.load()
    sql = gen.build_dev_seed(ref)
    members = ref["members"]
    # Keep the password already handed out, if this file was made before.
    previous = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
    found = re.search(r"extensions\.crypt\('([A-Za-z0-9_-]+)'", previous)
    password = found.group(1) if found else secrets.token_urlsafe(15)

    def swap(old, new, expected):
        nonlocal sql
        found = sql.count(old)
        if found != expected:
            raise SystemExit(f"generate_seed_sql.py output changed: expected {expected} x {old.strip()[:50]!r}, found {found}")
        sql = sql.replace(old, new)

    # One random password instead of the one written in the repo. pgcrypto
    # lives in the `extensions` schema on hosted Supabase.
    swap("crypt('paddock123', gen_salt('bf'))",
         f"extensions.crypt({gen.q(password)}, extensions.gen_salt('bf'))", len(members))
    # Hosted Supabase Auth refuses to sign in a user whose token columns are
    # NULL ("Database error querying schema"); they must be empty strings.
    swap("                        created_at, updated_at)\n",
         "                        created_at, updated_at, confirmation_token, recovery_token,\n"
         "                        email_change_token_new, email_change)\n", len(members))
    swap("        now(), now());\n", "        now(), now(), '', '', '', '');\n", len(members))
    # The old file began by deleting the demo logins; with roles in place the
    # last-President guard would refuse that. Refuse to run twice instead.
    swap("delete from auth.users where email like '%@sdumotorbike.test';\n", GUARD, 1)

    body = sql[sql.index("-- Stop, changing nothing"):]
    header = (
        "-- Mock data for Paddock Control — generated by scripts/make_mock_data_sql.py.\n"
        "-- Paste the whole file into Supabase → SQL Editor → Run. It loads the rulebook\n"
        "-- and season first (safe to re-run), then the demo team.\n"
        "-- Demo logins: <id>@sdumotorbike.test, all with the password printed when\n"
        "-- this file was generated. This file contains it: do not commit or share it.\n\n"
        "begin;\n\n"
    )
    # The reference data first: a project that only ran the schema migration
    # has no season, subsystems or rulebook for the mock data to hang off.
    reference = gen.build_reference(clauses, ref)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(header + reference + "\n" + body + "\ncommit;\n" + SUMMARY)

    board = {"mic", "and", "pio"}
    print(f"wrote {OUT}  ({os.path.getsize(OUT) // 1024} kB, {len(members)} people, "
          f"{len(ref['topics'])} topics, {len(ref['tasks'])} tasks, {len(ref['meetings'])} meetings)\n")
    print("Demo logins (all share one password):")
    for m in members:
        role = gen.privileged_role_for(m["role"]) if m["id"] in board else "member"
        print(f"  {m['id']}@sdumotorbike.test   {m['name']:<22} {m['role']:<28} → {role}")
    print(f"\nPassword: {password}")


if __name__ == "__main__":
    main()
