-- =============================================================================
--  Requirements Book outline and chapter progress.
--
--  book_chapters / book_subchapters hold the book's own structure — SECTION A–J,
--  their ARTICLEs and ANNEXes — with the numbering and headings exactly as the
--  table of contents of the verified PDF prints them (MS2627 Rev.01, sha256
--  53013ec6…8bf7669; generated by scripts/book/gen-book-outline.mjs). Reference
--  data per edition: members read it, nobody edits it through the API.
--
--  has_numbered_rules records whether the BOOK has numbered rules there. With
--  the Register's own count it separates three different things:
--    rules imported                     -> progress can be measured
--    book has rules, none imported      -> missing data (e.g. Section D,
--                                          the Electric category, not
--                                          imported for this eFuel season)
--    book has no numbered rules         -> a confirmed zero (glossary, annexes)
--
--  v_book_progress counts requirements per chapter and per subchapter from the
--  rules themselves (clauses.section / clauses.article — where the rulebook
--  prints them), never from department ownership, so reassigning a rule to a
--  department cannot move it between chapters or drop it from the count.
--  A requirement is a rule that places a duty on the team (is_team_duty, the
--  Register's default view); resolved = compliant, verified or not applicable
--  (the existing rule, as v_subteam_progress and the Register use it), with not
--  applicable also reported on its own. Chapter rows are counted directly over
--  their rules, so nothing is counted twice. Task completion plays no part.
--
--  Additive only: no existing row is changed or removed.
-- =============================================================================

create table if not exists book_chapters (
  regs_ref           text not null references regulation_documents(regs_ref) on delete restrict,
  code               text not null check (code ~ '^[A-Z]$'),
  label              text not null,
  heading            text not null,
  page               int  check (page is null or page > 0),
  sort_order         int  not null,
  has_numbered_rules boolean not null,
  primary key (regs_ref, code)
);

create table if not exists book_subchapters (
  regs_ref           text not null,
  chapter_code       text not null,
  kind               text not null check (kind in ('article', 'annex')),
  number             int  not null check (number > 0),
  label              text not null,
  heading            text not null,
  page               int  check (page is null or page > 0),
  sort_order         int  not null,
  has_numbered_rules boolean not null,
  primary key (regs_ref, chapter_code, kind, number),
  foreign key (regs_ref, chapter_code) references book_chapters(regs_ref, code) on delete restrict
);

comment on table book_chapters is
  'The chapters (SECTION A, B, …) of each regulations edition, numbered and titled exactly as its table of contents prints them. Reference data.';
comment on table book_subchapters is
  'The ARTICLEs and ANNEXes of each chapter, as the table of contents prints them. clauses (section, article) point at the article rows.';
comment on column book_chapters.has_numbered_rules is
  'Whether the book itself numbers rules in this chapter. False = a confirmed absence (glossary, annexes), not missing data.';

alter table book_chapters enable row level security;
alter table book_subchapters enable row level security;
revoke all on book_chapters, book_subchapters from anon;
revoke insert, update, delete, truncate, trigger, references on book_chapters, book_subchapters from authenticated;
grant select on book_chapters, book_subchapters to authenticated;
drop policy if exists member_read on book_chapters;
create policy member_read on book_chapters for select to authenticated using (is_member());
drop policy if exists member_read on book_subchapters;
create policy member_read on book_subchapters for select to authenticated using (is_member());

-- Adds the outline rows an edition is missing. Never overwrites or deletes: a
-- row that exists with different text is a conflict and aborts everything.
create or replace function maintenance.apply_book_outline(p_regs_ref text, p_chapters jsonb, p_subchapters jsonb)
returns jsonb
language plpgsql
set search_path = public
as $fn$
declare
  v_conflicts text[];
  v_chapters int;
  v_subchapters int;
begin
  if not exists (select 1 from regulation_documents where regs_ref = p_regs_ref) then
    raise exception 'apply_book_outline: no regulation_documents row for %', p_regs_ref using errcode = '23514';
  end if;

  with ch as (
    select e->>0 as code, e->>1 as label, e->>2 as heading, (e->>3)::int as page, (e->>4)::int as sort_order,
           (e->>5)::boolean as has_numbered_rules
    from jsonb_array_elements(p_chapters) e
  ), sc as (
    select e->>0 as chapter_code, e->>1 as kind, (e->>2)::int as number, e->>3 as label, e->>4 as heading,
           (e->>5)::int as page, (e->>6)::int as sort_order, (e->>7)::boolean as has_numbered_rules
    from jsonb_array_elements(p_subchapters) e
  )
  select array_agg(problem order by problem) into v_conflicts from (
    select format('chapter %s exists as "%s: %s", the book says "%s: %s"', b.code, b.label, b.heading, ch.label, ch.heading) as problem
      from ch join book_chapters b on b.regs_ref = p_regs_ref and b.code = ch.code
      where (b.label, b.heading) is distinct from (ch.label, ch.heading)
    union all
    select format('%s.%s %s exists as "%s", the book says "%s"', b.chapter_code, b.number, b.kind, b.heading, sc.heading)
      from sc join book_subchapters b on b.regs_ref = p_regs_ref and b.chapter_code = sc.chapter_code
                                      and b.kind = sc.kind and b.number = sc.number
      where (b.label, b.heading) is distinct from (sc.label, sc.heading)
  ) x;
  if v_conflicts is not null then
    raise exception E'Book outline refused, nothing changed:\n%', array_to_string(v_conflicts, E'\n') using errcode = '23514';
  end if;

  insert into book_chapters (regs_ref, code, label, heading, page, sort_order, has_numbered_rules)
  select p_regs_ref, e->>0, e->>1, e->>2, (e->>3)::int, (e->>4)::int, (e->>5)::boolean
  from jsonb_array_elements(p_chapters) e
  on conflict (regs_ref, code) do nothing;
  get diagnostics v_chapters = row_count;

  insert into book_subchapters (regs_ref, chapter_code, kind, number, label, heading, page, sort_order, has_numbered_rules)
  select p_regs_ref, e->>0, e->>1, (e->>2)::int, e->>3, e->>4, (e->>5)::int, (e->>6)::int, (e->>7)::boolean
  from jsonb_array_elements(p_subchapters) e
  on conflict (regs_ref, chapter_code, kind, number) do nothing;
  get diagnostics v_subchapters = row_count;

  -- Every imported rule of this edition must sit under a chapter and an
  -- article of the outline, or it would silently fall out of the progress.
  if exists (
    select 1 from clauses c
    where c.regs_ref = p_regs_ref
      and not exists (select 1 from book_subchapters s
                      where s.regs_ref = c.regs_ref and s.chapter_code = c.section
                        and s.kind = 'article' and s.number = c.article)) then
    raise exception 'apply_book_outline: % rule(s) of % have no article in the outline, e.g. %',
      (select count(*) from clauses c where c.regs_ref = p_regs_ref and not exists (
         select 1 from book_subchapters s where s.regs_ref = c.regs_ref and s.chapter_code = c.section
           and s.kind = 'article' and s.number = c.article)),
      p_regs_ref,
      (select min(c.clause_key) from clauses c where c.regs_ref = p_regs_ref and not exists (
         select 1 from book_subchapters s where s.regs_ref = c.regs_ref and s.chapter_code = c.section
           and s.kind = 'article' and s.number = c.article))
      using errcode = '23514';
  end if;

  return jsonb_build_object('regs_ref', p_regs_ref, 'chapters_added', v_chapters, 'subchapters_added', v_subchapters);
end
$fn$;

revoke all on function maintenance.apply_book_outline(text, jsonb, jsonb) from public;

-- Chapter and subchapter progress, per season (a season reads its own
-- edition). Rows for every outline entry, rules or not.
create or replace view v_book_progress with (security_invoker = on) as
with counts as (
  select s.id as season_id, c.section, c.article, grouping(c.article) as chapter_total,
         count(*)                                                                               as imported_rules,
         count(*) filter (where c.is_team_duty)                                                 as requirements,
         count(*) filter (where c.is_team_duty and cs.state in ('compliant', 'verified', 'na')) as resolved,
         count(*) filter (where c.is_team_duty and cs.state = 'na')                             as not_applicable,
         count(*) filter (where c.is_team_duty and cs.state = 'wip')                            as in_progress,
         count(*) filter (where c.is_team_duty and cs.state = 'blocked')                        as blocked
  from seasons s
  join clauses c on c.regs_ref = s.regs_ref
  left join clause_status cs on cs.clause_key = c.clause_key and cs.season_id = s.id
  group by grouping sets ((s.id, c.section), (s.id, c.section, c.article))
)
select s.id as season_id, ch.regs_ref, 'chapter'::text as level,
       ch.code as chapter_code, null::text as kind, null::int as number,
       ch.label, ch.heading, ch.page, ch.sort_order as chapter_sort, 0 as sort_order, ch.has_numbered_rules,
       coalesce(k.imported_rules, 0) as imported_rules, coalesce(k.requirements, 0) as requirements,
       coalesce(k.resolved, 0) as resolved, coalesce(k.not_applicable, 0) as not_applicable,
       coalesce(k.in_progress, 0) as in_progress, coalesce(k.blocked, 0) as blocked
from seasons s
join book_chapters ch on ch.regs_ref = s.regs_ref
left join counts k on k.season_id = s.id and k.section = ch.code and k.chapter_total = 1
union all
select s.id, sc.regs_ref, 'subchapter',
       sc.chapter_code, sc.kind, sc.number,
       sc.label, sc.heading, sc.page, ch.sort_order, sc.sort_order, sc.has_numbered_rules,
       coalesce(k.imported_rules, 0), coalesce(k.requirements, 0),
       coalesce(k.resolved, 0), coalesce(k.not_applicable, 0),
       coalesce(k.in_progress, 0), coalesce(k.blocked, 0)
from seasons s
join book_subchapters sc on sc.regs_ref = s.regs_ref
join book_chapters ch on ch.regs_ref = sc.regs_ref and ch.code = sc.chapter_code
left join counts k on k.season_id = s.id and sc.kind = 'article'
                  and k.section = sc.chapter_code and k.article = sc.number and k.chapter_total = 0;

comment on view v_book_progress is
  'Requirement progress per book chapter and subchapter, per season. Counted from the rules (section/article), never from departments or tasks.';

revoke all on v_book_progress from anon;
grant select on v_book_progress to authenticated;

-- The outline of MS2627 Rev.01, from its table of contents. Generated by
-- scripts/book/gen-book-outline.mjs; do not edit by hand.
do $do$
begin
  raise notice 'book outline: %', maintenance.apply_book_outline('MS2627 Rev.01',
-- <generated:book-chapters>
maintenance.checked_json($json$[
["A","SECTION A","ADMINISTRATIVE REGULATIONS",6,1,true],
["B","SECTION B","GENERAL TECHNICAL REGULATIONS",33,2,true],
["C","SECTION C","SPECIFIC TECHNICAL REGULATIONS FOR THE CATEGORY “MOTOSTUDENT eFUEL”",65,3,true],
["D","SECTION D","SPECIFIC TECHNICAL REGULATIONS FOR THE CATEGORY “MOTOSTUDENT ELECTRIC”",82,4,true],
["E","SECTION E","SCRUTINEERING",112,5,true],
["F","SECTION F","COMPETITION STRUCTURING",126,6,true],
["G","SECTION G","SPORTING REGULATIONS FOR MS2 PHASE",177,7,true],
["H","SECTION H","FINAL EVENT",205,8,true],
["I","SECTION I","MODIFICATIONS GLOSSARY",214,9,false],
["J","SECTION J","ANNEXES",215,10,false]
]$json$, '24d6b04d3824137a55fccaaad944ba46')
-- </generated:book-chapters>
  ,
-- <generated:book-subchapters>
maintenance.checked_json($json$[
["A","article",1,"ARTICLE 1","INTRODUCTION TO MOTOSTUDENT COMPETITION",7,1,true],
["A","article",2,"ARTICLE 2","APPLICATION OF THE MOTOSTUDENT REGULATIONS",14,2,true],
["A","article",3,"ARTICLE 3","PARTICIPATION REQUIREMENTS",18,3,true],
["A","article",4,"ARTICLE 4","MANUFACTURING THE MOTORBIKE",23,4,true],
["A","article",5,"ARTICLE 5","PARTICULARITIES FOR NON-EUROPEAN TEAMS",25,5,true],
["A","article",6,"ARTICLE 6","COMPETITION CALENDAR",28,6,true],
["A","article",7,"ARTICLE 7","COMMUNICATION BETWEEN TEAMS AND ORGANIZATION",30,7,true],
["A","article",8,"ARTICLE 8","OTHER COMPETITIONS",32,8,true],
["B","article",1,"ARTICLE 1","TECHNICAL REQUIREMENTS OF THE PROTOTYPE AND RESTRICTIONS",34,9,true],
["B","article",2,"ARTICLE 2","GENERAL DESIGN REQUIREMENTS",34,10,true],
["B","article",3,"ARTICLE 3","FRAME",38,11,true],
["B","article",4,"ARTICLE 4","FAIRING",40,12,true],
["B","article",5,"ARTICLE 5","HANDLEBARS AND FOOTRESTS",43,13,true],
["B","article",6,"ARTICLE 6","BRAKE SYSTEM",45,14,true],
["B","article",7,"ARTICLE 7","SUSPENSION AND DAMPERS",48,15,true],
["B","article",8,"ARTICLE 8","STEERING SYSTEM",49,16,true],
["B","article",9,"ARTICLE 9","RIMS AND TIRES",50,17,true],
["B","article",10,"ARTICLE 10","ELECTRONIC SYSTEMS",52,18,true],
["B","article",11,"ARTICLE 11","IDENTIFICATION, ADVERTISING AND COMPETITION NUMBERS",56,19,true],
["B","article",12,"ARTICLE 12","RIDER EQUIPMENT",61,20,true],
["C","article",1,"ARTICLE 1","ENGINE",66,21,true],
["C","article",2,"ARTICLE 2","AIR INTAKE SYSTEM",72,22,true],
["C","article",3,"ARTICLE 3","FUEL SUPPLY SYSTEM",73,23,true],
["C","article",4,"ARTICLE 4","FUEL AND LUBRICANTS",76,24,true],
["C","article",5,"ARTICLE 5","COOLING SYSTEM",77,25,true],
["C","article",6,"ARTICLE 6","EXHAUST SYSTEM",78,26,true],
["C","article",7,"ARTICLE 7","TRANSMISSION SYSTEM",79,27,true],
["C","article",8,"ARTICLE 8","ELECTRIC INSTALLATION",80,28,true],
["D","article",1,"ARTICLE 1","DEFINITIONS AND GENERAL ASPECTS",84,29,true],
["D","article",2,"ARTICLE 2","ELECTRIC MOTOR AND POWER DEMAND",86,30,true],
["D","article",3,"ARTICLE 3","ENERGY STORAGE",93,31,true],
["D","article",4,"ARTICLE 4","DISCONNECTION SYSTEMS AND CIRCUITS",97,32,true],
["D","article",5,"ARTICLE 5","BATTERY PACK CHARGING",103,33,true],
["D","article",6,"ARTICLE 6","GENERAL INSTALLATION AND WIRING",106,34,true],
["D","article",7,"ARTICLE 7","CONTROL AND CONTROL DEVICES",106,35,true],
["D","article",8,"ARTICLE 8","TRANSMISSION SYSTEM",109,36,true],
["D","article",9,"ARTICLE 9","COOLING SYSTEM",110,37,true],
["D","article",10,"ARTICLE 10","DOCUMENTATION OF THE PROTOTYPE",111,38,true],
["E","article",1,"ARTICLE 1","OBJECTIVE AND METHODOLOGY",113,39,true],
["E","article",2,"ARTICLE 2","ADMINISTRATIVE CHECK",114,40,true],
["E","article",3,"ARTICLE 3","STATIC SCRUTINEERING",116,41,true],
["E","article",4,"ARTICLE 4","STATIC SCRUTINEERING SPECIFIC TO “MOTOSTUDENT eFUEL” CATEGORY",119,42,true],
["E","article",5,"ARTICLE 5","STATIC SCRUTINEERING SPECIFIC TO “MOTOSTUDENT ELECTRIC” CATEGORY",120,43,true],
["E","article",6,"ARTICLE 6","DYNAMIC SAFETY CHECK",122,44,true],
["E","article",7,"ARTICLE 7","CHANGES AND REPAIRS",124,45,true],
["E","article",8,"ARTICLE 8","ADDITIONAL SCRUTINEERING ROUNDS",125,46,true],
["E","article",9,"ARTICLE 9","TIME CONTROL PROCEDURE",125,47,true],
["F","article",1,"ARTICLE 1","OBJECTIVES",128,48,true],
["F","article",2,"ARTICLE 2","PHASES OF THE COMPETITION",129,49,true],
["F","article",3,"ARTICLE 3","MS1 1st MILESTONE, TEAM PLAN",130,50,true],
["F","article",4,"ARTICLE 4","MS1 2nd MILESTONE, PRODUCT DEFINITION",133,51,true],
["F","article",5,"ARTICLE 5","MS1 3rd MILESTONE, INNOVATION",139,52,true],
["F","article",6,"ARTICLE 6","MS1 4th DELIVERY, PROTOTYPE CAD AND DRAWINGS",144,53,true],
["F","article",7,"ARTICLE 7","MS1 5TH MILESTONE, ECONOMICAL PLAN",149,54,true],
["F","article",8,"ARTICLE 8","MS1 6th MILESTONE, PITCH PRESENTATION",154,55,true],
["F","article",9,"ARTICLE 9","MS1 7th MILESTONE, FINAL EVENT PRESENTATION",157,56,true],
["F","article",10,"ARTICLE 10","MOTOSTUDENT ELECTRIC DELIVERIES",160,57,true],
["F","article",11,"ARTICLE 11","RIDER ELIGIBILITY DECLARATION",161,58,true],
["F","article",12,"ARTICLE 12","MS2 PHASE",161,59,true],
["F","article",13,"ARTICLE 13","MOTOSTUDENT AWARDS",170,60,true],
["F","article",14,"ARTICLE 14","DELIVERABLE SUBMISSIONS AND PENALTIES",174,61,true],
["G","article",1,"ARTICLE 1","GOALS AND CONDITIONS",178,62,true],
["G","article",2,"ARTICLE 2","RIDER",178,63,true],
["G","article",3,"ARTICLE 3","SPORT BEHAVIOUR",182,64,true],
["G","article",4,"ARTICLE 4","PRACTICE SESSIONS (INCLUDING WARM-UP)",185,65,true],
["G","article",5,"ARTICLE 5","GRID POSITIONS",187,66,true],
["G","article",6,"ARTICLE 6","RACES",189,67,true],
["G","article",7,"ARTICLE 7","PARC FERMÉ",201,68,true],
["G","article",8,"ARTICLE 8","ABANDONEMENT DURING THE EVENT",202,69,true],
["G","article",9,"ARTICLE 9","TEST 1, 2 & 3 BEHAVIOR",203,70,true],
["H","article",1,"ARTICLE 1","SCHEDULE",206,71,true],
["H","article",2,"ARTICLE 2","AREAS AND FACILITIES DURING THE FINAL EVENT",206,72,true],
["H","article",3,"ARTICLE 3","PARTICIPANT ACCREDITATION",209,73,true],
["H","article",4,"ARTICLE 4","BEHAVIOUR RULES",209,74,true],
["H","article",5,"ARTICLE 5","COMMUNICATION",211,75,true],
["H","article",6,"ARTICLE 6","ELECTRICAL SAFETY",212,76,true],
["J","annex",1,"ANNEX 1","CLAIMS AND IMPUGNATIONS FORM",216,77,false],
["J","annex",2,"ANNEX 2","MOTORLAND ARAGÓN – FIM GRAND PRIX INTERNATIONAL TRACK LAYOUT",217,78,false],
["J","annex",3,"ANNEX 3","INDICATIVE FINAL EVENT MAP (TO BE CONFIRMED)",218,79,false],
["J","annex",4,"ANNEX 4","COLLABORATION AGREEMENT",219,80,false],
["J","annex",5,"ANNEX 5","MOTOSTUDENT REGISTRATION PROCESS",220,81,false],
["J","annex",6,"ANNEX 6","ENGINE MANAGEMENT PROCEDURE",227,82,false],
["J","annex",7,"ANNEX 7","MOTOR/ENGINE TEMPORARY LOAN TERMS AND CONDITIONS",230,83,false],
["J","annex",8,"ANNEX 8","MODEL DECLARATION OF RESPONSIBLE FOR TIRES FOR THE TEAMS",234,84,false]
]$json$, '81bb64d3eff363a350a21f996eaf279e')
-- </generated:book-subchapters>
  );
end
$do$;
